# Generated by Django 5.1.2 on 2024-10-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klucz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Chusteczki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=120)),
                ('ilosc', models.IntegerField()),
                ('lokacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PierwAPP.skelp')),
            ],
        ),
    ]
